INSERT INTO categorias (nome_categoria, descricao) VALUES
('Celulares e Smartphones', 'Aparelhos celulares, smartphones e telefones móveis'),
('Informática', 'Equipamentos e componentes para informática em geral'),
('Notebooks e Ultrabooks', 'Notebooks, laptops e ultrabooks'),
('Computadores e PCs', 'Computadores de mesa e PCs completos'),
('Tablets e Leitores Digitais', 'Tablets e dispositivos de leitura digital'),
('TVs e Home Theater', 'Televisores, home theaters e equipamentos de vídeo'),
('Áudio e Som', 'Equipamentos de áudio, som e acessórios'),
('Eletrodomésticos', 'Eletrodomésticos para uso doméstico'),
('Eletroportáteis', 'Eletroportáteis para cozinha e limpeza'),
('Linha Branca', 'Eletrodomésticos de grande porte'),
('Acessórios para Celular', 'Capas, cabos, carregadores e acessórios para celular'),
('Acessórios para Informática', 'Acessórios para computadores e notebooks'),
('Games e Consoles', 'Consoles, jogos e acessórios gamers'),
('Periféricos', 'Periféricos como teclado, mouse, monitor e webcam'),
('Impressoras e Suprimentos', 'Impressoras, cartuchos e toners'),
('Câmeras e Filmadoras', 'Câmeras digitais, filmadoras e acessórios'),
('Casa Inteligente', 'Dispositivos de automação residencial'),
('Energia e Iluminação', 'Produtos de iluminação e energia elétrica'),
('Telefonia Fixa', 'Aparelhos e acessórios de telefonia fixa'),
('Cabos, Adaptadores e Conectores', 'Cabos, adaptadores e conectores em geral');
